version: '3'
services:
    payara:
        image: payara/server-full:5.2021.3
        volumes:
        - ./entrypoint.sh:/opt/payara/scripts/entrypoint.sh
        - ./set.sh:/opt/payara/scripts/set.sh
        - ./get.sh:/opt/payara/scripts/get.sh
        - ./pass:/opt/payara/.gfclient/pass

